import type { ScoutingVraag } from "./vragen";

// ─── Rood (leeftijd 16-18): 36 vragen, slider-schaal (6 per pijler) ───

export const VRAGEN_ROOD: ScoutingVraag[] = [
  {
    id: "sch_afstandsschot",
    pijler: "SCH",
    label: "Afstandsschot",
    vraagTekst: "Schiet krachtig en geplaatst van afstand",
  },
  {
    id: "sch_doorloopbal",
    pijler: "SCH",
    label: "Doorloopbal",
    vraagTekst: "Maakt doorloopballen onder hoge druk",
  },
  {
    id: "sch_schotkeuze",
    pijler: "SCH",
    label: "Schotkeuze",
    vraagTekst: "Kiest het optimale schot in elke situatie",
  },
  {
    id: "sch_penalty",
    pijler: "SCH",
    label: "Strafworp",
    vraagTekst: "Scoort strafworpen onder druk",
  },
  {
    id: "sch_variatie",
    pijler: "SCH",
    label: "Schotvariatie",
    vraagTekst: "Heeft meerdere schotvormen in het arsenaal",
  },
  {
    id: "sch_scorend_vermogen",
    pijler: "SCH",
    label: "Scorend vermogen",
    vraagTekst: "Is klinisch in de afronding",
  },
  {
    id: "aan_vrijlopen",
    pijler: "AAN",
    label: "Vrijlopen",
    vraagTekst: "Creëert ruimte door slim vrij te lopen",
  },
  {
    id: "aan_positie",
    pijler: "AAN",
    label: "Positiespel",
    vraagTekst: "Neemt dominante aanvalsposities in",
  },
  {
    id: "aan_dreigen",
    pijler: "AAN",
    label: "Dreigen",
    vraagTekst: "Dwingt verdedigers in onmogelijke keuzes",
  },
  {
    id: "aan_omschakeling",
    pijler: "AAN",
    label: "Omschakeling",
    vraagTekst: "Schakelt razendsnel om naar aanval",
  },
  {
    id: "aan_1_op_1",
    pijler: "AAN",
    label: "1-tegen-1",
    vraagTekst: "Wint duels in 1-tegen-1 situaties",
  },
  {
    id: "aan_spelcreatie",
    pijler: "AAN",
    label: "Spelcreatie",
    vraagTekst: "Creëert kansen voor medespelers",
  },
  {
    id: "pas_techniek",
    pijler: "PAS",
    label: "Passtechniek",
    vraagTekst: "Geeft technisch perfecte passes",
  },
  {
    id: "pas_overzicht",
    pijler: "PAS",
    label: "Overzicht",
    vraagTekst: "Heeft volledig overzicht over het speelveld",
  },
  {
    id: "pas_besluitvorming",
    pijler: "PAS",
    label: "Besluitvorming",
    vraagTekst: "Maakt onder druk de juiste keuzes",
  },
  {
    id: "pas_balbehandeling",
    pijler: "PAS",
    label: "Balbehandeling",
    vraagTekst: "Controleert de bal foutloos onder hoge druk",
  },
  {
    id: "pas_aanname",
    pijler: "PAS",
    label: "Aanname",
    vraagTekst: "Neemt de bal in volle sprint feilloos aan",
  },
  {
    id: "pas_creativiteit",
    pijler: "PAS",
    label: "Creativiteit",
    vraagTekst: "Verrast met onverwachte passes en acties",
  },
  {
    id: "ver_dekken",
    pijler: "VER",
    label: "Dekken",
    vraagTekst: "Dekt de tegenstander strak en gedisciplineerd",
  },
  {
    id: "ver_onderscheppen",
    pijler: "VER",
    label: "Onderscheppen",
    vraagTekst: "Anticipeert en onderschept gevaarlijke ballen",
  },
  {
    id: "ver_rebound",
    pijler: "VER",
    label: "Rebound",
    vraagTekst: "Domineert de rebound-zone",
  },
  {
    id: "ver_communicatie",
    pijler: "VER",
    label: "Communicatie",
    vraagTekst: "Organiseert de verdediging door communicatie",
  },
  {
    id: "ver_blok",
    pijler: "VER",
    label: "Blokken",
    vraagTekst: "Blokkeert effectief schoten",
  },
  {
    id: "ver_druk_zetten",
    pijler: "VER",
    label: "Druk zetten",
    vraagTekst: "Zet continu druk op de bal",
  },
  {
    id: "fys_snelheid",
    pijler: "FYS",
    label: "Snelheid",
    vraagTekst: "Is explosief en snel over korte afstand",
  },
  {
    id: "fys_uithoudingsvermogen",
    pijler: "FYS",
    label: "Uithoudingsvermogen",
    vraagTekst: "Presteert constant op hoog niveau gedurende de hele wedstrijd",
  },
  {
    id: "fys_kracht",
    pijler: "FYS",
    label: "Kracht",
    vraagTekst: "Is fysiek sterk in duels en bij het schieten",
  },
  {
    id: "fys_beweeglijkheid",
    pijler: "FYS",
    label: "Beweeglijkheid",
    vraagTekst: "Beweegt soepel met snelle richtingsveranderingen",
  },
  {
    id: "fys_sprongkracht",
    pijler: "FYS",
    label: "Sprongkracht",
    vraagTekst: "Heeft goede sprongkracht bij rebounds en schoten",
  },
  {
    id: "fys_herstel",
    pijler: "FYS",
    label: "Herstel",
    vraagTekst: "Herstelt snel na intensieve acties",
  },
  {
    id: "men_inzet",
    pijler: "MEN",
    label: "Inzet",
    vraagTekst: "Geeft altijd maximale inzet, ook bij achterstand",
  },
  {
    id: "men_concentratie",
    pijler: "MEN",
    label: "Concentratie",
    vraagTekst: "Blijft gefocust in beslissende momenten",
  },
  {
    id: "men_leiderschap",
    pijler: "MEN",
    label: "Leiderschap",
    vraagTekst: "Neemt de leiding en inspireert teamgenoten",
  },
  {
    id: "men_weerbaarheid",
    pijler: "MEN",
    label: "Weerbaarheid",
    vraagTekst: "Blijft presteren onder druk en na tegenslagen",
  },
  {
    id: "men_spelintelligentie",
    pijler: "MEN",
    label: "Spelintelligentie",
    vraagTekst: "Leest het spel en anticipeert op situaties",
  },
  {
    id: "men_wedstrijdmentaliteit",
    pijler: "MEN",
    label: "Wedstrijdmentaliteit",
    vraagTekst: "Presteert beter naarmate de wedstrijd belangrijker is",
  },
];
