import type { TeamCategorie, Kleur, TeamType } from "@oranje-wit/database";
import { prisma, teamId } from "./types";
import { logger } from "@oranje-wit/types";

interface TeamDef {
  nr: number;
  naam: string;
  alias: string | null;
  categorie: TeamCategorie;
  kleur: Kleur | null;
  teamType: TeamType;
  defaultOmvang: number;
  scenarioNote: string;
}

export const TEAM_DEFS: TeamDef[] = [
  {
    nr: 1,
    naam: "Senioren 1",
    alias: "S1",
    categorie: "SENIOREN",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 10,
    scenarioNote: "Standaard vol team",
  },
  {
    nr: 2,
    naam: "Senioren 2",
    alias: "S2",
    categorie: "SENIOREN",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 8,
    scenarioNote: "Net-aan",
  },
  {
    nr: 3,
    naam: "Senioren 3 (A)",
    alias: "S3",
    categorie: "A_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 10,
    scenarioNote: "Wedstrijdsport",
  },
  {
    nr: 4,
    naam: "Senioren 4 (B)",
    alias: "S4",
    categorie: "B_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 9,
    scenarioNote: "Korfbalplezier",
  },
  {
    nr: 5,
    naam: "Recreanten",
    alias: "RC",
    categorie: "B_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 8,
    scenarioNote: "RECREANT-status spelers",
  },
  {
    nr: 6,
    naam: "Midweek 1",
    alias: "MW1",
    categorie: "B_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 8,
    scenarioNote: "OVERIG type",
  },
  {
    nr: 7,
    naam: "U19-1",
    alias: "U19-1",
    categorie: "A_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 10,
    scenarioNote: "TOP jeugd",
  },
  {
    nr: 8,
    naam: "U19-2",
    alias: "U19-2",
    categorie: "B_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 9,
    scenarioNote: "Standaard jeugd",
  },
  {
    nr: 9,
    naam: "U17-1",
    alias: "U17-1",
    categorie: "A_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 10,
    scenarioNote: "TOP jeugd",
  },
  {
    nr: 10,
    naam: "U17-2",
    alias: "U17-2",
    categorie: "B_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 8,
    scenarioNote: "Standaard jeugd",
  },
  {
    nr: 11,
    naam: "U15-1",
    alias: "U15-1",
    categorie: "A_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 10,
    scenarioNote: "TOP jeugd",
  },
  {
    nr: 12,
    naam: "U15-2",
    alias: "U15-2",
    categorie: "B_CATEGORIE",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 8,
    scenarioNote: "Standaard jeugd",
  },
  {
    nr: 13,
    naam: "Rood-1",
    alias: "R1",
    categorie: "B_CATEGORIE",
    kleur: "ROOD",
    teamType: "ACHTTAL",
    defaultOmvang: 9,
    scenarioNote: "Korfbalplezier",
  },
  {
    nr: 14,
    naam: "Rood-2",
    alias: "R2",
    categorie: "B_CATEGORIE",
    kleur: "ROOD",
    teamType: "ACHTTAL",
    defaultOmvang: 8,
    scenarioNote: "Standaard jeugd",
  },
  {
    nr: 15,
    naam: "Oranje-1",
    alias: "O1",
    categorie: "B_CATEGORIE",
    kleur: "ORANJE",
    teamType: "ACHTTAL",
    defaultOmvang: 9,
    scenarioNote: "Ontwikkelhart",
  },
  {
    nr: 16,
    naam: "Oranje-2",
    alias: "O2",
    categorie: "B_CATEGORIE",
    kleur: "ORANJE",
    teamType: "ACHTTAL",
    defaultOmvang: 9,
    scenarioNote: "Standaard jeugd",
  },
  {
    nr: 17,
    naam: "Geel-1",
    alias: "G1",
    categorie: "B_CATEGORIE",
    kleur: "GEEL",
    teamType: "ACHTTAL",
    defaultOmvang: 9,
    scenarioNote: "Ontwikkelhart",
  },
  {
    nr: 18,
    naam: "Geel-2",
    alias: "G2",
    categorie: "B_CATEGORIE",
    kleur: "GEEL",
    teamType: "ACHTTAL",
    defaultOmvang: 8,
    scenarioNote: "Standaard jeugd",
  },
  {
    nr: 19,
    naam: "Groen-1",
    alias: "Gr1",
    categorie: "B_CATEGORIE",
    kleur: "GROEN",
    teamType: "VIERTAL",
    defaultOmvang: 6,
    scenarioNote: "Kweekvijver",
  },
  {
    nr: 20,
    naam: "Groen-2",
    alias: "Gr2",
    categorie: "B_CATEGORIE",
    kleur: "GROEN",
    teamType: "VIERTAL",
    defaultOmvang: 5,
    scenarioNote: "Standaard jeugd",
  },
  {
    nr: 21,
    naam: "Blauw-1",
    alias: "B1",
    categorie: "B_CATEGORIE",
    kleur: "BLAUW",
    teamType: "VIERTAL",
    defaultOmvang: 6,
    scenarioNote: "Kweekvijver",
  },
  {
    nr: 22,
    naam: "Blauw-2",
    alias: "B2",
    categorie: "B_CATEGORIE",
    kleur: "BLAUW",
    teamType: "VIERTAL",
    defaultOmvang: 4,
    scenarioNote: "Standaard jeugd",
  },
  {
    nr: 23,
    naam: "Kangoeroes",
    alias: "K",
    categorie: "B_CATEGORIE",
    kleur: "PAARS",
    teamType: "VIERTAL",
    defaultOmvang: 8,
    scenarioNote: "Kweekvijver jongste",
  },
  {
    nr: 24,
    naam: "EDGE-LEEG",
    alias: "EDGE-LEEG",
    categorie: "SENIOREN",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 0,
    scenarioNote: "Validatie ORANJE (leeg)",
  },
  {
    nr: 25,
    naam: "EDGE-ONDER",
    alias: "EDGE-ONDER",
    categorie: "SENIOREN",
    kleur: null,
    teamType: "ACHTTAL",
    defaultOmvang: 6,
    scenarioNote: "Validatie ROOD onder-min",
  },
];

export async function seedTeams(versieId: string): Promise<void> {
  logger.info("[seed-teams] 25 teams aanmaken");
  for (const def of TEAM_DEFS) {
    await prisma.team.upsert({
      where: { id: teamId(def.nr) },
      create: {
        id: teamId(def.nr),
        naam: def.naam,
        alias: def.alias,
        categorie: def.categorie,
        kleur: def.kleur,
        teamType: def.teamType,
        versieId,
      },
      update: {
        naam: def.naam,
        alias: def.alias,
        categorie: def.categorie,
        kleur: def.kleur,
        teamType: def.teamType,
        versieId,
      },
    });
  }
  logger.info(`[seed-teams] klaar — ${TEAM_DEFS.length} teams`);
}
